# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0002_auto_20170623_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='secrets.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='secret',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='secrets.Secret'),
        ),
    ]
