# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0003_auto_20170623_1611'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='like',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='secret',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
