# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-26 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0004_auto_20170623_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='secrets.User'),
            preserve_default=False,
        ),
    ]
